project:
  type: book

book:
  title: "Anwendungsbaustein Energiedatenanalyse"
  author:
    - Lukas Arnold
    - Simone Arnold
    - Florian Bagemihl
    - Matthias Baitsch
    - Marc Fehr
    - Franca Hollmann
    - Maik Poetzsch
    - Sebastian Seipel
  date: today
  language: de-DE
  downloads: [pdf]
  repo-url: "https://github.com/bausteine-der-datenanalyse/a-energiedatenanalyse"
  repo-actions: [source]
  favicon: "skript/00-bilder/favicon_bcd_new.svg"
  sidebar:
    title: "Anwendungsbaustein Energiedatenanalyse"
    logo: "skript/00-bilder/logo_with_text_new.svg"

## Inhaltsverzeichnis / table of contents
toc: true
toc-title:  |
  Anwendungsbaustein Energiedatenanalyse 

  ![](skript/00-bilder/logo_with_text_new.svg)
number-sections: true
number-depth: 2

## Bibliographie / bibliography
bibliography: skript/bibliography.bib
biblio-style: authoryear

fig-width: 6
fig-asp: 0.618

format:
  html:
    theme: [cosmo, theme.scss]
    lang: de
    language:
      de:
        crossref-imp-title: "Definition"
        crossref-imp-prefix: "Definition"
        crossref-lst-title: "Code-Block"
        crossref-lst-prefix: "Code-Block"
        crossref-nte-title: "Beispiel"
        crossref-nte-prefix: "Beispiel"
        crossref-tip-title: "Tipp"
        crossref-tip-prefix: "Tipp"
        crossref-wrn-title: "Hinweis"
        crossref-wrn-prefix: "Hinweis"
        tbl-cap-location: bottom
  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    biblio-title: Quellen
    lang: de
    toc-depth: 1

execute:
  freeze: auto

profile:
  default: full
  group: 
    - [full]

